# Cheatsheet

Condensed to quickly translate among libraries.

In [1]:
# Numpy (np)
import numpy as np

# TensorFlow (tf)
import tensorflow as tf

# pyTorch (pt)
import torch


## Tensors

In [2]:
lols = [
    [
        [0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [10, 11, 12, 13, 14],
    ],
    [
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
    ],
]

In [3]:
# np
tnp = np.array(lols)

# pt
tpt = torch.tensor(lols)
# or
#tpt = torch.from_numpy(tnp)

In [4]:
tnp.shape, tpt.shape

((2, 3, 5), torch.Size([2, 3, 5]))

### Ones, zeros, random,

In [5]:
shape = (2, 3, 5)

In [6]:
# np
tnp_ones = np.ones(shape)
tnp_zeros = np.zeros(shape)

# TODO: seed
tnp_rand_floats = np.random.random(shape)  # uniform [0.0, 1.0)
tnp_rand_floats = np.random.normal(size=shape)  # standard normal
tnp_rand_ints = np.random.randint(low=0, high=100, size=shape)

## or using the random number generator
#rng = np.random.default_rng()
#tnp_rand_floats = rng.random(size=shape)  # uniform [0.0, 1.0)
#tnp_rand_floats = rng.uniform(low=0.0, high=1.0, size=shape)  # uniform
#tnp_rand_floats = rng.normal(size=shape)  # standard normal
#tnp_rand_ints = rng.integers(low=0, high=100, size=shape)

In [7]:
# pt
tpt_ones = torch.ones(shape)
tpt_zeros = torch.zeros(shape)

torch.manual_seed(42) # Set the seed to an arbitrary integer
tpt_rand_floats = torch.rand(shape)  # uniform [0.0, 1.0)
tpt_rand_floats = torch.randn(shape)  # standard normal
tpt_rand_ints = torch.randint(low=0, high=100, size=shape)

## mimick another tensor
#tpt_rand_floats = torch.rand_like(tpt_ones, dtype=torch.float)
#tpt_rand_floats = torch.randn_like(tpt_ones, dtype=torch.float)
## TODO: tpt_rand_ints = torch.randint_like(torch.tensor(tpt_ones, dtype=torch.int))

In [8]:

torch.tensor(tpt_ones, dtype=torch.int)

C:\Users\camil.LAPTOP-FHSQ7SV9\AppData\Local\Temp\ipykernel_55168\629437886.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(tpt_ones, dtype=torch.int)


tensor([[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]], dtype=torch.int32)

### Operations

In [9]:
# np
print(tnp.sum())

# pt
print(tpt.sum())

435
tensor(435)


## [TODO] Devices

In [10]:
# pt
print(
    torch.cuda.is_available(),
    torch.cuda.device_count(),
    #torch.cuda.get_device_name(0),
    torch.cuda.device(0)
)

False 0 <torch.cuda.device object at 0x000001EE07954AD0>


In [11]:
#tpt_ones = tpt_ones.to('cuda')

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tpt_ones = tpt_ones.to(device)
print(tpt_ones.device)
tpt_ones.cpu().numpy()

cpu


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)

## Backpropagation

In [12]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
f = 3 * a**3 - b**2

$f = 3a^3 - b^2, \qquad \partial f/  \partial a = 9a^2, \qquad \partial f/  \partial b = -2b$

In [13]:
f.backward(gradient=torch.tensor([1, 1]))

In [14]:
print(9 * a**2, a.grad)
print(-2 * b, b.grad)

tensor([36., 81.], grad_fn=<MulBackward0>) tensor([36., 81.])
tensor([-12.,  -8.], grad_fn=<MulBackward0>) tensor([-12.,  -8.])
